### PR TITLE
add build with docker

### PR DESCRIPTION
**Pull request by Vaayne**

### CODE REVIEW

**Comment by craigary** [comment]
Hi there, sorry for the late reply~

Unfortunately I don't know much about docker, let me test this on my machine~

**Comment by craigary** [comment]
Hi, I was trying to run this on my machine, it works fine, however, I am not able to load the Gravater image on the post page.

I have no idea about docker whatsoever 🤪 would you mind to take a look?

**Comment by Vaayne** [comment]
Hi, @craigary please try it again, it should be fixed.

**Comment by craigary** [comment]
LGTM, merged! Since I have no idea about docker whatsoever, let me mark this as "unofficial" method~
Thank you for the PR!

**Comment by Vaayne** [comment]
@JOduMonT I think it was caused by https://github.com/craigary/nobelium/issues/178
For now main branch was updated, you can pull main and try again.

**Pull request merged**
